/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ceid.db.tvondemandclientsideapp;

import java.sql.*;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author dimet
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Serif CJK JP Black", 0, 24)); // NOI18N
        jLabel1.setText("Registration Form");

        jTextField1.setText("Enter your First Name");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Fist Name:");

        jLabel3.setText("Last Name:");

        jLabel4.setText("Email:");

        jLabel5.setText("Address:");

        jLabel6.setText("City:");

        jLabel7.setText("Country:");

        jLabel8.setText("Postal Code:");

        jTextField3.setText("Enter your email");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField4.setText("Enter your address");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jTextField5.setText("Enter your Postal Code");

        jTextField6.setText("Enter your City");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "France", "Germany", "Italy", "Spain", "United Kingdom", "Greece" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jCheckBox1.setText("I aggree to the terms and conditions and the privacy policy");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Register");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Registration type:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "film", "series", "both" }));

        jLabel10.setText("District:");

        jTextField7.setText("Enter your District");
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });

        jLabel11.setText("Phone number:");

        jTextField8.setText("Enter your phone number");

        jLabel12.setText("Password:");

        jTextField9.setText("Enter your Last Name");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jPasswordField1.setText("jPasswordField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jTextField9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addGap(30, 30, 30))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel4)
                                                .addComponent(jLabel5)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel11)
                                                .addComponent(jLabel7))
                                            .addGap(51, 51, 51)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField3)
                                        .addComponent(jTextField4)
                                        .addComponent(jTextField5)
                                        .addComponent(jTextField8)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jComboBox1, 0, 100, Short.MAX_VALUE))
                                            .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jButton1)))
                .addContainerGap(70, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel11))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected())
            agreetoterms = true;
        else agreetoterms = false;
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        boolean empty_fields = true;
        ArrayList<String> rdata = this.GetRData();
         for(String s: rdata)
            {
               if(s.isEmpty())
                   empty_fields = false;
                   
            }
        
         if(!empty_fields)
            JOptionPane.showMessageDialog(new JFrame(),"You must fill every field for your registration");
         else
         {
        if(!agreetoterms)
            JOptionPane.showMessageDialog(new JFrame(),"Please agree to the licensed terms in order for the registration to complete");
        else 
        {
            
           
      
      try(Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/tvondemandv2", "tester", "@Toor1234");)
      {
            
         
          
          String query1 = "Select email from user where email like '"+rdata.get(2)+"'";
          Statement sts2 = con.createStatement();
          ResultSet resultnew =sts2.executeQuery(query1);
          
       if(resultnew.next())  // elenxos an yparxei egrafi me ayto to  email
       {
                JOptionPane.showMessageDialog(new JFrame(),"this email is use");
              
       }
       else  //an den yparxei ayto to email tote ginete h egrafi
       {
         
          
          String squery = "select city_id from city where city like '"+rdata.get(5)+"'";
          Statement sts = con.createStatement();
          Statement sts1 = con.createStatement();
         
          ResultSet sresult = sts.executeQuery(squery);
          String addr_id = "";
          
        
          
          
          if(sresult.next()) //city is already in our database.
          {
             ResultSet result1 =  sts.executeQuery("select address_id from address where address like '"+rdata.get(3)+"' and postal_code like '"+rdata.get(4)+"'");
             if(result1.next()) //addreess is already in our database
            {  
                sts1.executeUpdate("Insert into user Values(Default,'"+rdata.get(2)+"','"+rdata.get(10)+"')");
                ResultSet getu_id =sts.executeQuery("Select u_id from user where email like '"+rdata.get(2)+"'");  
                getu_id.next();//perno to u_id na to valo ston customer san customer_id
                
                 ResultSet ad_id =  sts1.executeQuery("select address_id from address where address like '"+rdata.get(3)+"' and postal_code like '"+rdata.get(4)+"'");
                 ad_id.next();//perno xana to address_id na to valo ston customer
                
                 sts.executeUpdate("Insert into customer Values("+getu_id.getInt(1)+",'"+rdata.get(0)+"','"+rdata.get(1)+"','"+rdata.get(2)+"',"+ad_id.getInt(1)+",1,'2007-08-24 14:33:05','"+rdata.get(9)+"')");
                
              
            }
            else
            {   
               
                ResultSet city_id = sts.executeQuery("Select city_id from city where city like '"+rdata.get(5)+"'");
                city_id.next();
                sts.executeUpdate("Insert into address values(DEFAULT,'"+rdata.get(3)+"','"+rdata.get(6)+"',"+city_id.getInt(1)+",'"+rdata.get(4)+"','"+rdata.get(7)+"')");

                ResultSet address_id = sts.executeQuery("select address_id from address where address like '"+rdata.get(3)+"' and postal_code like '"+rdata.get(4)+"'");
                address_id.next();
                
                //after creating city and the corresponding address
                sts1.executeUpdate("Insert into user Values(Default,'"+rdata.get(2)+"','"+rdata.get(10)+"')");
                ResultSet getu_id =sts.executeQuery("Select u_id from user where email like '"+rdata.get(2)+"'");  
                getu_id.next();//perno to u_id na to valo ston customer san customer_id
                 
                 ResultSet ad_id =  sts1.executeQuery("select address_id from address where address like '"+rdata.get(3)+"' and postal_code like '"+rdata.get(4)+"'");
                 ad_id.next();//perno xana to address_id na to valo ston customer
                
                
                sts.executeUpdate("Insert into customer Values("+getu_id.getInt(1)+",'"+rdata.get(0)+"','"+rdata.get(1)+"','"+rdata.get(2)+"',"+ad_id.getInt(1)+",1,'2007-08-24 14:33:05','"+rdata.get(9)+"')");
            }         
              
          }
          else 
          {
                ResultSet country_id =  sts.executeQuery("select country_id from country where country like '"+rdata.get(8)+"'");
                System.out.println(rdata.get(8));
                if(country_id.next())  
                    sts.execute("Insert into city values(DEFAULT,'"+rdata.get(5)+"',"+country_id.getInt(1)+")");
               
                    
               
                     
                
                
                ResultSet city_id = sts.executeQuery("Select city_id from city where city like '"+rdata.get(5)+"'");
                if(city_id.next())
                    sts.executeUpdate("Insert into address values(DEFAULT,'"+rdata.get(3)+"','"+rdata.get(6)+"',"+city_id.getInt(1)+",'"+rdata.get(4)+"','"+rdata.get(7)+"')");
                
                ResultSet address_id = sts.executeQuery("select address_id from address where address like '"+rdata.get(3)+"' and postal_code like '"+rdata.get(4)+"'");
               
                
                if(address_id.next())//after creating city and the corresponding address
                 {
                sts.executeUpdate("Insert into user Values(DEFAULT,'"+rdata.get(2)+"','"+rdata.get(10)+"')");
               
                 ResultSet getu_id =sts.executeQuery("Select u_id from user where email like '"+rdata.get(2)+"'");  
                 getu_id.next();//perno to u_id na to valo ston customer san customer_id
                 
                 ResultSet ad_id =  sts1.executeQuery("select address_id from address where address like '"+rdata.get(3)+"' and postal_code like '"+rdata.get(4)+"'");
                 ad_id.next();//perno xana to address_id na to valo ston customer
                 
                 sts1.executeUpdate("Insert into customer Values("+getu_id.getInt(1)+",'"+rdata.get(0)+"','"+rdata.get(1)+"','"+rdata.get(2)+"',"+ad_id.getInt(1)+", 1, '2007-08-24 14:33:05','"+rdata.get(9)+"')");
               }
              
              address_id.close();
              city_id.close();
              country_id.close();
             // con.close();  
                
          }
          
          JOptionPane.showMessageDialog(new JFrame(),"You successfully registered in our service. Enjoy content!");
          
          
          
      }
      }
      catch (SQLException e)
      {
          e.printStackTrace();
      }
      finally
      {
          // we must add the parametrized constructor here.
          updateCurrentUser(rdata.get(2));
          this.dispose();
          Customer1 cust = new Customer1(rdata.get(2));
          cust.setVisible(true);
          
      }
        }
     }
    }//GEN-LAST:event_jButton1ActionPerformed

     private void updateCurrentUser(String email)
   {
       try(Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/tvondemandv2", "tester", "@Toor1234");)
        {   
    
            String query = "Update cuser set email ='"+ email +"'";
            //dinei ena precompiled query sthn bash se peripotsh poy yparxei polles fores.
            PreparedStatement statement = con.prepareStatement(query);
            statement.executeUpdate();
            
        }
        catch (SQLException e)
        {
            e.printStackTrace();
        }
       
   }
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed
    
    
    
  public ArrayList<String> GetRData()
    {
        ArrayList<String> data = new ArrayList<String>();
        
        if(jTextField1.getText().length()>45)//firt name     0
        data.add(jTextField1.getText().substring(0,44));
        else
        data.add(jTextField1.getText());
     
        if(jTextField9.getText().length()>45) // last name   1
        data.add(jTextField9.getText().substring(0,44));
        else
        data.add(jTextField9.getText());
        
        if(jTextField3.getText().length()>50)   //email    2
        data.add(jTextField3.getText().substring(0,49));
        else
        data.add(jTextField3.getText());
        
        if(jTextField4.getText().length()>50)   // address  3
        data.add(jTextField4.getText().substring(0,49));
        else
        data.add(jTextField4.getText());
        
        if(jTextField5.getText().length()>10)    // postal code  4
        data.add(jTextField5.getText().substring(0,8));
        else
        data.add(jTextField5.getText());
       
        if(jTextField6.getText().length()>50)  // city      5
        data.add(jTextField6.getText().substring(0,49));
        else
        data.add(jTextField6.getText());
            
        if(jTextField7.getText().length()>20)  //district      6
        data.add(jTextField7.getText().substring(0,19));
        else
        data.add(jTextField7.getText());
        
        if(jTextField8.getText().length()>20) //phone       7
        data.add(jTextField8.getText().substring(0,19));
        else
        data.add(jTextField8.getText()); 
       
        data.add(String.valueOf(jComboBox1.getSelectedItem()));
        data.add(String.valueOf(jComboBox2.getSelectedItem()));
        
        if(String.valueOf(jPasswordField1.getPassword()).length()>10)
        data.add(String.valueOf(jPasswordField1.getPassword()).substring(0,10));
        else
        data.add(String.valueOf(jPasswordField1.getPassword()));
        
      
      
        
        
        if(!agreetoterms)
            return new ArrayList<String>();
        
        return data;
    }
   
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }
    
    private boolean agreetoterms;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
